### ISSUE TITLE
No such schema error during configuration when installed from PYPI

### ISSUE THREAD

**Issue by aral** [Stunkymonkey/nautilus-open-any-terminal#10]
1. Install via PYPI instructions on Pop!_OS 19.10 (~ Ubuntu 19.10)
2. Run:
    ```
    gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal kitty
    ```

Error:

```
No such schema “com.github.stunkymonkey.nautilus-open-any-terminal”
```

I do see the Open Gnome-Terminal here and Open Tilix here options in the context menu in Nautilus.

**Comment by Stunkymonkey** [comment]
if you installed it systemwide can you run:
`sudo glib-compile-schemas /usr/local/share/glib-2.0/schemas`

**Comment by aral** [comment]
Right, so I figured out a workaround. It seems that at least on my system, they settings schema is being installed into:

```
~/.local/share/glib-2.0/schemas/
```

Once I realised that, all I had to do was to run:

```sh
glib-compile-schemas /home/aral/.local/share/glib-2.0/schemas/
```

And then restart Nautilus again (`nautilus -q`).

And then I was able to include Kitty using the same line as in the issue:

```sh
gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal kitty
```

Would you like a PR to the readme to mention this?

**Comment by aral** [comment]
PS. Regarding your previous comment, @Stunkymonkey, even with a systemwide install, the schema is being copied into `~/.local/share/glib-2.0/schemas/` for me.

**Comment by aral** [comment]
PPS. Thanks for making this ;)

**Comment by Stunkymonkey** [comment]
I definitely have to dig deeper, why this is put into the home directory. The README would be a temporary solution.
I will have to adjust the `setup.py`. 

Thanks for reporting :wink:

**Comment by aral** [comment]
Agree + cool, I’ll leave it in your capable hands then :) Thanks again!

**Comment by Stunkymonkey** [comment]
since the `glib-compile-schemas` should be done by package maintainers I would not like to include this in the setup.py. instead there is now an information displayed to do so by hand.
[setup.py#33](https://github.com/Stunkymonkey/nautilus-open-any-terminal/blob/master/setup.py#L33) I hope this will help in the future.

**Comment by Stunkymonkey** [comment]
new release will come in the next days
