### ISSUE TITLE
problem with opening directories that contain "

### ISSUE THREAD

**Issue by moshiur05** [Stunkymonkey/nautilus-open-any-terminal#11]
I'm using this extension to open alacritty in arch linux. I noticed that when i try to open a directory like /home/user/"new_dir" the extension simply uses cd "/home/user/new_dir" instead of "/home/user/\\"new_dir\\"".

**Comment by Stunkymonkey** [comment]
yes I can reproduce this.

This and the next weeks are going to be quite busy. So do not expect this to be fixed immediatly.

**Comment by Stunkymonkey** [comment]
found some time. new release should fix it
