### ISSUE TITLE
Issue with blackbox terminal not launching in Fedora 39 Workstation.

### ISSUE THREAD

**Issue by trxharu** [Stunkymonkey/nautilus-open-any-terminal#116]
### Issue
Recently installed `nautilus-open-any-terminal` to use it with Blackbox terminal. But after setting up everything, terminal is not launching.

### Workaround
Found out that blackbox terminal's binary has different name `blackbox-terminal` instead of `blackbox`. Resolved it after creating a symlink under `/usr/bin`.

**Comment by Stunkymonkey** [comment]
fixed via #102 . included in the next release.
