### ISSUE TITLE
Doesn't show open option in menu

### ISSUE THREAD

**Issue by dustdfg** [Stunkymonkey/nautilus-open-any-terminal#125]
Hello!

I installed the deb package from the github and it doesn't work for me. I use Debian12 + sway + foot.
I even don't see the Open option in the menu for default gnome-terminal. I also installed `python3-nautilus` package

I performed:
`glib-compile-schemas /usr/share/glib-2.0/schemas`
`nautilus -q`

But it doesn't work.

I just thought... Does it work only in GNOME?

**Comment by lvxnull** [comment]
If you start nautilus from the terminal, what's the output on stdout/stderr? Any errors?

**Comment by dustdfg** [comment]
> If you start nautilus from the terminal, what's the output on stdout/stderr? Any errors?

I usually ran it from `wofi` so I didn't saw any errors but when I run in terminal I see:
```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus_open_any_terminal.py", line 26, in <module>
    require_version("Gtk", "4.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Gtk not available for version 4.0
```

**Comment by lvxnull** [comment]
try installing `gir1.2-gtk-4.0` and see if it works

**Comment by dustdfg** [comment]
> try installing `gir1.2-gtk-4.0` and see if it works

Yeah, I just googled and found it. It helped! Thanks. It think it should be added to instructions list in the readme

**Comment by lvxnull** [comment]
I've already updated the package. I'll update the readme soon.
