### ISSUE TITLE
Two entries in Nautilus popup menu

### ISSUE THREAD

**Issue by bulletmark** [Stunkymonkey/nautilus-open-any-terminal#13]
I just saw [this](https://www.omgubuntu.co.uk/2020/07/open-folder-in-terminal-ubuntu-plugin) in my feed today. I am running up to date Arch Linux so I installed this extension from the AUR @ version 0.2.8-1. Then I did:

    gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal tilix

When I right click on a directory in Nautilus I get an entry for "Open in Terminal" and 2 entries for "Open in Tilix". Likewise when I right click on the background of an open directory pane I get a single "Open in Terminal" but 2 entries for "Open Tilix Here".

**Comment by Stunkymonkey** [comment]
- "Open in Terminal" is provided by gnome. I am not sure how to remove it, because other things could break.
- "Open in Tilix" is provided by tilix itself: [here the code for it](https://github.com/gnunn1/tilix/blob/master/data/nautilus/open-tilix.py)
- "Open Tilix Here" is the one provided by this plugin.

So I think everything is working as expected. In your case just uninstall this plugin and you will only see one entry in the popup.

**Comment by bulletmark** [comment]
"Open in Terminal" is expected. I only stated here to be clear that it exists. The issue I am reporting here is the fact that both of those Tilix options appear TWICE each in the pop menu, as seen [here](https://imgur.com/a/3AXfvT0).

Also, if I simply `yay -Rsn nautilus-open-any-terminal` then all the Tilix options in Nautilus in both places disappear so it certainly appears they are both due to your extension.

**Comment by Stunkymonkey** [comment]
oh okay that was a misunderstanding.

I will look into this. Thanks for reporting

**Comment by devcroc** [comment]
"Open in terminal" can be removed by uninstalling gnome-terminal.

**Comment by Stunkymonkey** [comment]
okay. should I add a note a t the bottom about gnome-terminal?

**Comment by bulletmark** [comment]
What has gnome-terminal got to do with this bug? As I showed [in the screenshot](https://imgur.com/a/3AXfvT0) I referenced above, the bug here is about the 2 "Open in Tilix" entries added by this extension.

**Comment by Stunkymonkey** [comment]
nothing at all
but saying thanks is no problem for me.
I already opened an issue on the tilix repo side.
there is not much activity on the repo.
so do not expect it to be solved quickly.

**Comment by bulletmark** [comment]
So are you saying that it is a Tilix bug? You have not stated that here previously. As I said above, installing this extension makes BOTH "Open in Tilix" menu items as per that screenshot appear, and removing this extension makes BOTH those disappear.

**Comment by Stunkymonkey** [comment]
currently i am having difficulties to debug this.
Maybe it is, maybe not.
I asked for help to debug this.

**Comment by bulletmark** [comment]
It would have made sense for you to add a link here to [that issue](https://github.com/gnunn1/tilix/issues/1919).

**Comment by Stunkymonkey** [comment]
@bulletmark i am unable to reproduce this at my machine.
when you install both tilix and this plugin can you please show me the files at:
`/usr/local/share/glib-2.0/schemas/`?
`/usr/share/nautilus-python/extensions/`?

**Comment by bulletmark** [comment]
Sorry, not using this extension anymore. Feel free to close this bug.

**Comment by w00zie** [comment]
Facing the same problem here, with urxvt.

 <img src="https://user-images.githubusercontent.com/18007677/97745621-6dfe0c00-1ae9-11eb-9809-dc88a4f2a483.jpg" width="250" height="250">

I actually tried to install this extension twice: the first time I was inside a virtualenv and, hence, I did not install the extension system-wide. The second time I installed it in my system Pip but now I'm having two entries in the popup menu.

This would not be a big deal for me but, when I execute the shortcut, two terminals are launched.

How can I eliminate one of the two entries and the relative action?

Thanks!

**Comment by Stunkymonkey** [comment]
i guess you just did install it system-wide and user-wide at the same time. This way two entrys are coming up. Try uninstalling one of them.

**Comment by w00zie** [comment]
Duh I didn't notice that this extension had two types of installations (user and system): uninstalled one of them, working now! Thanks and sorry for bothering you

**Comment by Tamas-Toth-ebola** [comment]
Hi!

I'm, having the 'duplicated Tilix' problem in Ubuntu 22.10 _(beta)_ only with `tilix` so with `gnome-terminal` already uninstalled.

I'm trying to describe eveything in the background:

**Available terminals:**
```
sudo apt list tilix                                  
Listing... Done
tilix/kinetic,now 1.9.5-2 amd64 [installed]

sudo apt list gnome-terminal
Listing... Done
gnome-terminal/kinetic 3.46.1-2ubuntu1 amd64

sudo apt list gnome-console 
Listing... Done
gnome-console/kinetic 43~beta-0ubuntu1 amd64
```
**The proper and only one is selected:**
```
sudo update-alternatives --config x-terminal-emulator
There are 5 choices for the alternative x-terminal-emulator (providing /usr/bin/x-terminal-emulator).

  Selection    Path                    Priority   Status
------------------------------------------------------------
* 0            /usr/bin/tilix.wrapper   30        auto mode
  1            /usr/bin/koi8rxterm      20        manual mode
  2            /usr/bin/lxterm          30        manual mode
  3            /usr/bin/tilix.wrapper   30        manual mode
  4            /usr/bin/uxterm          20        manual mode
  5            /usr/bin/xterm           20        manual mode

```
**Corresponding Python - Nautilus installed:**
```
sudo apt list python3-nautilus     
Listing... Done
python3-nautilus/kinetic,now 4.0-1 amd64 [installed]
```
**Your plugin is only once installed:**

![image](https://user-images.githubusercontent.com/25765137/193534253-f3c903b4-db9e-41bf-bf9d-f777eb93488a.png)

**And the practice:**

After installing version 0.4.0 of your plugin via `pip` _(as user package)_ I get **2 instances** of the corresponding references in my 'Nautilus':

![image](https://user-images.githubusercontent.com/25765137/193534667-0ff9ef83-9179-4a68-8b2a-75209069bcbb.png)

But after uninstalling it there is **none**...

In theory this can be my fault, but I don't know yet how and why?!

Could you please help me, help me to debug it?

Thanks in advance!

**Comment by Stunkymonkey** [comment]
`tilix` itself supplies this entry automatically. So for me the solution sounds like: uninstall this plugin.
