### ISSUE TITLE
Context menu has the "Open terminal here" entry duplicated

### ISSUE THREAD

**Issue by neslinesli93** [Stunkymonkey/nautilus-open-any-terminal#132]
Hi, just found out about this extension and it's awesome!
I'm using it with wezterm on popos, and i don't understand why there are two entries when i right click:
- `Open Wez's terminal emulator here`
- `Open in WezTerm`

Shouldn't it be just one? There used to be a context entry for `tilix` too but after uninstalling it, the entry went away.

I installed wezterm via `apt install wezterm` and below are my distro settings as well as the settings found in the `dconf-editor`

```
Distributor ID: Pop
Description:    Pop!_OS 22.04 LTS
Release:        22.04
Codename:       jammy
```

![image](https://github.com/Stunkymonkey/nautilus-open-any-terminal/assets/1112539/a4b50a89-54a6-4c72-bfab-076140665ada)

**Comment by Stunkymonkey** [comment]
- `Open Wez's terminal emulator here` if from this extension: https://github.com/Stunkymonkey/nautilus-open-any-terminal/blob/master/nautilus_open_any_terminal/nautilus_open_any_terminal.py#L88
- `Open in WezTerm` is from the emulator itself: https://github.com/wez/wezterm/blob/main/assets/wezterm-nautilus.py#L59.

uninstall one of them (I guess my extension...) and you will only see a single entry.

**Comment by neslinesli93** [comment]
Thank you so much for taking the time to investigate and point me to the right resources, not everyone does all of that :)

Basically I got into this issue: https://github.com/wez/wezterm/issues/4275
