### ISSUE TITLE
Ptyxis package should be `org.gnome.Ptyxis.Devel` instead of `org.gnome.Ptyxis`

### ISSUE THREAD

**Issue by jonerrr** [Stunkymonkey/nautilus-open-any-terminal#134]
I think the flatpak package specified for ptyxis is invalid. Instead of being `org.gnome.Ptyxis`, it should be `org.gnome.Ptyxis.Devel` (as shown in their [README](https://gitlab.gnome.org/chergert/ptyxis#installation)).

**Comment by Stunkymonkey** [comment]
I think this is just because all nightly packages are called this way: https://wiki.gnome.org/Apps/Nightly

**Comment by jonerrr** [comment]
Yes, but currently, there is only a nightly version available. I think until it has a stable release, it should be changed to `org.gnome.Ptyxis.Devel` (unless there is a stable version I'm completely missing or if there's an easy way to rename the package).

**Comment by Stunkymonkey** [comment]
Ok I have an idea. What about adding this as a seconds terminal emulator: `ptyxis-nightly` ? that would work for you. see: #137

**Comment by jonerrr** [comment]
Just tested and it works, Thank you :)
