### ISSUE TITLE
Warp terminal not being set as the selected terminal

### ISSUE THREAD

**Issue by vihangatheturtle** [Stunkymonkey/nautilus-open-any-terminal#135]
I tried `gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal xterm` (this worked)

but then I tried `gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal warp` (this did not work). I do have the Warp terminal installed. Instead the option in nautilus stayed as "Open In XTerm".

Not sure where I can find logs for this, can provide if you can provide a directory for them.

Thanks!

**Comment by lvxnull** [comment]
Close nautilus with `nautilus -q` then run nautilus from the console and paste the output here

**Comment by vihangatheturtle** [comment]
that seems to have fixed it, thanks anyway!
