### ISSUE TITLE
Open Black Box Here not working

### ISSUE THREAD

**Issue by Retch** [Stunkymonkey/nautilus-open-any-terminal#138]
![image](https://github.com/Stunkymonkey/nautilus-open-any-terminal/assets/16291785/ebb2b80c-6f7f-4ced-b7d7-4d7989de6573)

Installed [nautilus-open-any-terminal](https://github.com/Stunkymonkey/nautilus-open-any-terminal) via pip --user. Blackbox is installed not as a flatpak and set via dconf editor.

Nothing happens when i click "Open Black Box here".

![image](https://github.com/Stunkymonkey/nautilus-open-any-terminal/assets/16291785/e1959dcf-90d6-40e8-8e98-4d7df1368e60)

**Comment by lvxnull** [comment]
Close nautilus with `nautilus -q` and open it through a terminal. If there are any errors, send them here.

**Comment by Retch** [comment]
> Close nautilus with `nautilus -q` and open it through a terminal. If there are any errors, send them here.

I already done that, also restarted. I don't get any error, and i don't find logs.

**Comment by Retch** [comment]
> Close nautilus with `nautilus -q` and open it through a terminal. If there are any errors, send them here.

Sorry, got now what you meant.

![image](https://github.com/Stunkymonkey/nautilus-open-any-terminal/assets/16291785/98283483-1427-4dea-b7b2-eb301f314edb)

**Comment by lvxnull** [comment]
What's your distro? Do you know what is the name of the blackbox binary on your system?

**Comment by Retch** [comment]
I'm on Ultramarine (Fedora)

![image](https://github.com/Stunkymonkey/nautilus-open-any-terminal/assets/16291785/3d46b5fa-d703-43bf-9ca0-2a37e72c8a47)
This is how blackbox should open when not installed as a flatpak

**Comment by lvxnull** [comment]
What's the output of `cat /etc/os-release`?

**Comment by Retch** [comment]
![image](https://github.com/Stunkymonkey/nautilus-open-any-terminal/assets/16291785/0aab4b35-ef70-49ef-a331-b9f2f4f462fb)

**Comment by Retch** [comment]
https://packages.fedoraproject.org/pkgs/blackbox-terminal/blackbox-terminal/

**Comment by lvxnull** [comment]
This happens because we check for fedora based only on the `ID` field, ignoring `ID_LIKE`. Soon I'll submit a PR that fixes this.

**Comment by Retch** [comment]
> This happens because we check for fedora based only on the `ID` field, ignoring `ID_LIKE`. Soon I'll submit a PR that fixes this.

I understand, thank you :)

**Comment by Stunkymonkey** [comment]
i guess the `distro_id` string is not equal to `"fedora"` here, but should be:
https://github.com/Stunkymonkey/nautilus-open-any-terminal/blob/master/nautilus_open_any_terminal/nautilus_open_any_terminal.py#L229

we should change it to something like: `distro_id() in ["fedora", "ultramarine"]`? not sure about the exact value.

**Comment by Stunkymonkey** [comment]
@lvxnull should we make a new release? some fixes are on master

**Comment by lvxnull** [comment]
Yes. The only question is if it should be a minor or major release.

**Comment by lvxnull** [comment]
@Retch the fix was already merged onto master. You can install from git to fix your issue immediately or wait until we release a new release.
@Stunkymonkey should it be a major or minor release?

**Comment by Retch** [comment]
@lvxnull Thank you very much

**Comment by Stunkymonkey** [comment]
@lvxnull only minor or bugfix. no breaking changes happened.
