### ISSUE TITLE
[Feature Request] Add Hyper terminal support

### ISSUE THREAD

**Issue by TMartinPPC** [Stunkymonkey/nautilus-open-any-terminal#14]
Awesome extension. Would love to see official support for Hyper terminal added.

https://hyper.is/

**Comment by Stunkymonkey** [comment]
Thanks. is added in the version: 0.2.9

**Comment by NotoriousNico** [comment]
@Stunkymonkey 

Sorry to bring up a four-year-old issue, but could you please update the "Supported Terminal Emulators" of your README?
Hyper isn't mentioned there.

**Comment by lvxnull2** [comment]
Hyper support was removed because at some point hyper stopped respecting the parent process's cwd while not having any command line option for specifying it. Support will be added again when its possible, sorry for the iconvenience

**Comment by NotoriousNico** [comment]
I see, thank you for the explanation. And no worries.
Appreciate your response!
