### ISSUE TITLE
[FEATURE SUGGESTION] Consider disabling default open in terminal to avoid confusion.

### ISSUE THREAD

**Issue by NanashiTheNameless** [Stunkymonkey/nautilus-open-any-terminal#143]
one way it can be done is with 
`sudo mv -vi /usr/lib/x86_64-linux-gnu/nautilus/extensions-3.0/libterminal-nautilus.so{,.bak}`

it exists at `/usr/lib/x86_64-linux-gnu/nautilus/extensions-3.0/libterminal-nautilus.so` by default

**Comment by lvxnull** [comment]
Package management is out of scope of this project. If you want to remove the stock gnome terminal extension, you can do so using your distro's package manager.
