### ISSUE TITLE
Custom terminal aliases

### ISSUE THREAD

**Issue by p5** [Stunkymonkey/nautilus-open-any-terminal#146]
Hello team!

It would be great if the extension could set a custom gsettings option to change the alias of the terminal that appears in the context menu.

For example, as a distribution maintainer I want to ship Ptyxis terminal, but would prefer it to be called just "Terminal" in the context menus so it's more understandable for the user.
This could be an option like `terminal-alias` or `terminal-custom-name`.  If not set, use "Open in Ptyxis".  If it is set, the menu should display "Open in \<ALIAS>".

![image](https://github.com/Stunkymonkey/nautilus-open-any-terminal/assets/46304672/34e9d92d-3664-43d8-b9de-97160fd813b2)

**Comment by Stunkymonkey** [comment]
I have mixed feeling about this. I get the idea behind it, but I am seeing a bunch of unneeded ssues in this repo.

With the current way we can easily spot the problem by getting a screenshot.
With your proposed method debugging could get more complicated.

Assume the case:
you install terminal `A` and change the "alias" to `"A-Terminal"` and then switch to `B` but it still shows `A-Terminal`. Seems very unintuitive.

Same as with `gnome-terminal` how would we distinguish it with our extension or any another application.

**Comment by p5** [comment]
I completely understand, and agree with the increase in effort it may take to debug issues.
Feel free to close this issue if it's not something you feel would fit in here.

**Comment by namefailed** [comment]
I was looking for this feature. I just want it to say "Open Terminal Here" not "Open kitty Here" it's a little visually unappealing. Just my 2cents.

**Comment by namefailed** [comment]
> I was looking for this feature. I just want it to say "Open Terminal Here" not "Open kitty Here" it's a little visually unappealing. Just my 2cents.

I even tried to set an alias alias Terminal="kitty" and setting as Terminal, but that doesn't work.

**Comment by Sayan505** [comment]
How about the idea of making a new dconf key called "use-generic-terminal-name" of type "b" for a toggle b/w "Open Terminal Here" vs "Open \<yourterminal> Here" @Stunkymonkey?

**Comment by lvxnull** [comment]
This could work. The generic terminal name could even be translatable using
our existing translation framework. Might make a PR soon.
