### ISSUE TITLE
Add support for Prompt / Ptyxis

### ISSUE THREAD

**Issue by sebastiaanfranken** [Stunkymonkey/nautilus-open-any-terminal#147]
I've been using your extension for a while, and I am very happy with it! Recently I have switched to Prompt / Ptyxis as a terminal though and that is not a valid choice with your extension. So, that's why I've opened this issue. Can it be added? Chances are high it'll replace GNOME Terminal(kgx), though that's not 100% sure yet

**Comment by Stunkymonkey** [comment]
hey @sebastiaanfranken

I am assuing you are using flatpack with the `org.gnome.Ptyxis.Devel`? You then need to set it to `ptyxis-nightly` as in https://github.com/Stunkymonkey/nautilus-open-any-terminal/blob/master/nautilus_open_any_terminal/nautilus_open_any_terminal.py#L79 because there is not an official release for ptyxis out yet.

And have the latest version (0.5.1) installed.

**Comment by sebastiaanfranken** [comment]
> hey @sebastiaanfranken
> 
> I am assuing you are using flatpack with the `org.gnome.Ptyxis.Devel`? You then need to set it to `ptyxis-nightly` as in https://github.com/Stunkymonkey/nautilus-open-any-terminal/blob/master/nautilus_open_any_terminal/nautilus_open_any_terminal.py#L79 because there is not an official release for ptyxis out yet.
> 
> And have the latest version (0.5.1) installed.

Yes, `flatpak --user` to be exact. Thanks for the fast response, will try

**Comment by sebastiaanfranken** [comment]
Ok, extra / more info. It shows up now, but it doesn't open in the correct folder. It always opens in ~. Setting the flatpak option back to "system" makes it not even start the terminal anymore. Am I doing something wrong?

**Comment by lvxnull** [comment]
Can you check if my PR fixes your issue?

**Comment by sebastiaanfranken** [comment]
> Can you check if my PR fixes your issue?

It does, but only if there is no instance of ptyxis already opened

**Comment by lvxnull** [comment]
If you start nautilus from a terminal are there any errors?

**Comment by sebastiaanfranken** [comment]
For clarity, I removed the original extension, installed your PR, rebooted. Following that I opened Nautilus and navigated to my Downloads folder, right clicked and selected "open with ptyxis". That worked, it opened it in the right folder. After that I navigated (in Nautilus) to my Templates folder and did the same. Ptyxis did not open a new window/tab, nor did it switch the already running one. I closed ptyxis, and redid the steps. That time it worked.

**Comment by lvxnull** [comment]
> For clarity, I removed the original extension, installed your PR, rebooted. Following that I opened Nautilus and navigated to my Downloads folder, right clicked and selected "open with ptyxis". That worked, it opened it in the right folder. After that I navigated (in Nautilus) to my Templates folder and did the same. Ptyxis did not open a new window/tab, nor did it switch the already running one. I closed ptyxis, and redid the steps. That time it worked.
This means the PR fixes your issue, right?

**Comment by sebastiaanfranken** [comment]
> > For clarity, I removed the original extension, installed your PR, rebooted. Following that I opened Nautilus and navigated to my Downloads folder, right clicked and selected "open with ptyxis". That worked, it opened it in the right folder. After that I navigated (in Nautilus) to my Templates folder and did the same. Ptyxis did not open a new window/tab, nor did it switch the already running one. I closed ptyxis, and redid the steps. That time it worked.
> 
> This means the PR fixes your issue, right?

Half of the time.

**Comment by lvxnull** [comment]
@sebastiaanfranken Go to ptyxis settings > profile > edit your current profile > set "Preserve working directory" to Always and see if it works then.
