### ISSUE TITLE
Add Guake support

### ISSUE THREAD

**Issue by AbdElraoufSabri** [Stunkymonkey/nautilus-open-any-terminal#15]
Please add guake support

**Comment by AbdElraoufSabri** [comment]
I created a PR for this issue: #16

**Comment by Stunkymonkey** [comment]
sorry for responding so late. I would like to add support for it.

Currently i am on a short vacation, so it will take me some time (maybe 3 days) until i am back at my pc.

**Comment by AbdElraoufSabri** [comment]
I forgot to update the README file

**Comment by Stunkymonkey** [comment]
i already added it. thanks for your work

**Comment by AbdElraoufSabri** [comment]
You are welcome bro ^^ great repo it's. Though I think we need to make the installation instructions more concise and clear. I'll try making it better when I just have the time.
