### ISSUE TITLE
Port the project to other file managers

### ISSUE THREAD

**Issue by cfgnunes** [Stunkymonkey/nautilus-open-any-terminal#154]
Hi! Thanks for the project!

I have a similar project in:
https://github.com/cfgnunes/nautilus-scripts

I'm considering migrating it to Python, but before I proceed, I'm curious if there's a possibility of adapting your project to other file managers.
Could you please provide some insights or suggestions on this matter?

**Comment by lvxnull** [comment]
It wouldn't be hard to port this project to other nautilus forks such as nemo, just import it as `FileManager` if `get_required_version("<file manager name>")` isn't None. For other file managers, you would have to rewrite the code that creates the context menu entry for launching the terminal.

**Comment by Stunkymonkey** [comment]
@cfgnunes I guess your question is answered (you gave a thumbs up). Otherwise please report back.
