### ISSUE TITLE
Open Remote {terminal} Here - does not follow the "New Tab" setting

### ISSUE THREAD

**Issue by arigit** [Stunkymonkey/nautilus-open-any-terminal#166]
When selecting "Open Remote {terminal} Here" in the context menu (testing with ptyxis), the "New-tab" setting in dconf is ignored and a new window is opened every time. 
Can the new-tab setting be followed, or a new setting for remote windows be included in dconf? (new-tab-for-remote)

**Comment by lvxnull** [comment]
I've submitted a PR that fixes this that should work fine with ptyxis but I haven't tested this. You might want to install from my branch and check if this fixes your issue, but further testing with more terminals will be required before we merge this.

**Comment by arigit** [comment]
As mentioned in the pull request, I have tested your branch with both ptyxis and tilix and it works fine. The new-tab setting is followed. Thanks!
