### ISSUE TITLE
Not getting "open terminal here"

### ISSUE THREAD

**Issue by vaibd** [Stunkymonkey/nautilus-open-any-terminal#169]
I'm not getting the option "open terminal here".

Here's how I did it in NixOS:

 ` programs.dconf.enable = true; (in config.nix)
   dconf.settings = { (in home manager)
      "com/github/stunkymonkey/nautilus-open-any-terminal" = {
        terminal = "kitty";
      };
   };`

Have installed nautilus-python as well. I wasn't getting that option before either.

**Comment by vaibd** [comment]
Thanks it worked, pathsToLink wasn't set.

**Comment by Stunkymonkey** [comment]
@jtojnar I remember you having some experience with extensions. would it be fine to add the `pathsToLink` to?: https://github.com/NixOS/nixpkgs/blob/157a32caba6f58cf147a5b10ef063599f559c9f5/nixos/modules/programs/nautilus-open-any-terminal.nix#L20

**Comment by jtojnar** [comment]
Might be a good idea to put it into https://github.com/NixOS/nixpkgs/pull/319535

**Comment by Stunkymonkey** [comment]
Awesome. :heart_eyes:  Thanks for the response here.
