### ISSUE TITLE
Remove item from menu?

### ISSUE THREAD

**Issue by tiago138** [Stunkymonkey/nautilus-open-any-terminal#170]
How do I remove item from the menu?

**Comment by lvxnull** [comment]
Can you please be more specific about what exactly you want removed?

**Comment by Tiago138** [comment]
> Can you please be more specific about what exactly you want removed?
It add two open terminal here in my menu how do I remove it?

**Comment by lvxnull** [comment]
Have you uninstalled the gnome terminal specific extension?

**Comment by Stunkymonkey** [comment]
ping @Tiago138

**Comment by Tiago138** [comment]
> Have you uninstalled the gnome terminal specific extension?

I was trying to configure kitty terminal but it did not add kitty, a uninstalled kit and installed it again and now I have two open kitty here options

**Comment by Stunkymonkey** [comment]
how did you install the extension? might be, that you installed it system-wide & user-wide.

**Comment by Tiago138** [comment]
I installed it user-wide but it did not add kitty open terminal here, then I tried to add kitty again and it add another open terminal here. then I removed kitty and installed it again and now I have two kitty options.

I think I did install system-wide & user-wide because it did not work the first time.

**Comment by Stunkymonkey** [comment]
then you need to uninstall one of them. Recompile the schemas and there is only one context-entry.

**Comment by Tiago138** [comment]
When I try any using one of this two 
```
make uninstall scheme
sudo make uninstall scheme
```
I get ```No rule to make target 'uninstall'.  Stop.```

**Comment by Stunkymonkey** [comment]
try `make uninstall-common`

**Comment by lvxnull** [comment]
> When I try any using one of this two
> 
> ```
> make uninstall scheme
> sudo make uninstall scheme
> ```
> 
> I get `No rule to make target 'uninstall'. Stop.`

Are you sure you're installing the latest version of this project?

**Comment by tiago138** [comment]
> Are you sure you're installing the latest version of this project?

I am using version 0.5.1
I did pip uninstall nautilus-open-any-terminal and sudo pip uninstall nautilus-open-any-terminal
it removed the two options from the menu
But doing pip install --user nautilus-open-any-terminal nautilus does not open anymore
I am using pop-os 22.04

**Comment by lvxnull** [comment]
> > Are you sure you're installing the latest version of this project?
> 
> I am using version 0.5.1 I did pip uninstall nautilus-open-any-terminal and sudo pip uninstall nautilus-open-any-terminal it removed the two options from the menu But doing pip install --user nautilus-open-any-terminal nautilus does not open anymore I am using pop-os 22.04

Please install from source or from the deb packages available on the latest release and see if the issue persists

**Comment by tiago138** [comment]
> Please install from source or from the deb packages available on the latest release and see if the issue persists

The version nautilus-extension-any-terminal_0.6.0-1_all.deb it nautilus does not open after installation

Version nautilus-extension-any-terminal_0.5.1-2_all.deb works fine.

**Comment by lvxnull** [comment]
If you try running nautilus from a terminal is there any output?

**Comment by tiago138** [comment]
> If you try running nautilus from a terminal is there any output?

This is the output.

```
open-any-terminal: terminal is set to "kitty" opening a new window 

(org.gnome.Nautilus:193068): Gtk-WARNING **: 18:11:39.514: Theme directory apps@2x/22 of theme WhiteSur-yellow-dark has no size field


(org.gnome.Nautilus:193068): Gtk-WARNING **: 18:11:39.514: Theme directory apps@2x/32 of theme WhiteSur-yellow-dark has no size field


(org.gnome.Nautilus:193068): Gtk-WARNING **: 18:11:39.514: Theme directory preferences@2x/22 of theme WhiteSur-yellow-dark has no size field


(org.gnome.Nautilus:193068): GLib-GIO-ERROR **: 18:11:39.648: Settings schema 'com.github.stunkymonkey.nautilus-open-any-terminal' does not contain a key named 'use-generic-terminal-name'
zsh: trace trap (core dumped)  nautilus
```

**Comment by TheShepsMT89** [comment]
> The version nautilus-extension-any-terminal_0.6.0-1_all.deb nautilus does not open after installation

I encountered a similar issue to yours. In my case, I was using version 0.5 installed via pip, and upon updating to the latest version, I encountered the error `Settings schema 'com.github.stunkymonkey.nautilus-open-any-terminal' does not contain a key named 'use-generic-terminal-name'`.  I saw that the new version of the plugin had added new keys to the application schema.

Download [the latest schema file](https://raw.githubusercontent.com/Stunkymonkey/nautilus-open-any-terminal/master/nautilus_open_any_terminal/schemas/com.github.stunkymonkey.nautilus-open-any-terminal.gschema.xml) from the repository.

Depending on whether you installed the plugin globally or locally, copy the downloaded file to the appropriate directory.

- **System-wide Installation**:

```bash
sudo cp com.github.stunkymonkey.nautilus-open-any-terminal.gschema.xml /usr/share/glib-2.0/schemas/
```

- **User-level Installation**:

```bash
cp com.github.stunkymonkey.nautilus-open-any-terminal.gschema.xml ~/.local/share/glib-2.0/schemas/
```

Once the XML file is in the appropriate directory, compile the schema.

- **System-wide**:

```bash
sudo glib-compile-schemas /usr/share/glib-2.0/schemas
```

- **User-level**:

```bash
glib-compile-schemas ~/.local/share/glib-2.0/schemas/
```

Finally, restart Nautilus with `nautilus -q` for the changes to take effect. This should make Nautilus work again.

**Comment by lvxnull** [comment]
Just running `sudo glib-compile-schemas /usr/share/glib-2.0/schemas` should be enough.

**Comment by lvxnull** [comment]
It seems makedeb doesn't have an equivalent for alpm hooks and also doesn't support post install/upgrade scripts. Because I am not familiar with other packaging tools for debian, I won't be able to fix this. The source code for the debian package is currently [here](https://mpr.makedeb.org/nautilus-extension-any-terminal.git), if anyone finds a solution I will happily apply it there.

**Comment by tiago138** [comment]
> Just running `sudo glib-compile-schemas /usr/share/glib-2.0/schemas` should be enough.

It worked for me.
