### ISSUE TITLE
error: app/org.gnome.Ptyxis/x86_64/master not installed

### ISSUE THREAD

**Issue by kimjongbing** [Stunkymonkey/nautilus-open-any-terminal#175]
I installed this from the AUR and when I select Ptyxis from the dropdown I get:
error: app/org.gnome.Ptyxis/x86_64/master not installed

I have the stable version installed. It seems to try to open the nightly version still though. My installed version is app.devsuite.Ptyxis.

My workaround has just been to replace the flatpak path under "nightly" to point to the stable version.

**Comment by lvxnull** [comment]
The master branch already has this fixed already but the latest release does not. Please install from source instead.

**Comment by Stunkymonkey** [comment]
@lvxnull should we release a new version for this?

**Comment by lvxnull** [comment]
Yes, we can do this now or after #168 is merged.
