### ISSUE TITLE
Can't modify settings

### ISSUE THREAD

**Issue by juanda1306** [Stunkymonkey/nautilus-open-any-terminal#18]
After installing the extension (I tried both via pip and from the script in the tools folder, and both user and systemwide installations) I can't change the settings via dconf-editor neither via commandline.

Installing via the script in the tool folder I get this error:
`juan@pop-os:~/Downloads/nautilus-open-any-terminal$ sudo tools/update-extension-system.sh install
'nautilus_open_any_terminal/open_any_terminal_extension.py' -> '/usr/share/nautilus-python/extensions/open_any_terminal_extension.py'`

Then trying to change the settings via terminal:
`juan@pop-os:~$ gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal alacritty
No such schema “com.github.stunkymonkey.nautilus-open-any-terminal”`

And via dconf-editor I just can't find the stunkymonkey folder.

OS: Pop! OS, latest version, based on Ubuntu 20.04.

**Comment by Stunkymonkey** [comment]
did you run a `glib-compile-schemas` command? (for recompiling the schemas)

if this is missing the options can not be set.

**Comment by Stunkymonkey** [comment]
fixed by 3e3450f
