### ISSUE TITLE
Can't open ipv6 gvfs mounts locally

### ISSUE THREAD

**Issue by Plamper** [Stunkymonkey/nautilus-open-any-terminal#186]
When I try to open gvfs mounts locally, it either silently fails or drops me into my home directory. 

Inspecting the logs, I got `FileNotFoundError: [Errno 2] No such file or directory: '/run/user/1000/gvfs/smb-share:server=[<ipv6-adress>],share=<username>'` for a mount over ipv6 address. The real path has all brackets and colons replaced by %5B for [ %5D for ] %3A for each of the colons. 

On all mounts with hostname or ipv4 address, I get simply dropped into my home directory without any error whatsoever. Remote Terminal works fine. This is probably an issue with ptyxis, although I already set Preserve Working Directory to always. I can open the `/run/user/1000/gvfs` folder in ptyxis, but not its subdirectories.

**Comment by Plamper** [comment]
OK, the second one seems to be a ptyxis bug, as I always get dropped into my home folder when running `ptyxis --new-window` in a gvfs folder. In all other folders, this does not occur.

**Comment by Plamper** [comment]
Strangely, this works when supplying a shell via `-x`. For example, `ptyxis --new-window -x fish` will not reset to the home directory. I will report this upstream.

**Comment by Plamper** [comment]
The second part was indeed a ptyxis issue and has already been fixed, but I think the ipv6 issue is still present.

**Comment by lvxnull** [comment]
For some reason ptyxis urldecodes paths given to it via the command line. I think you should report this as well.
