### ISSUE TITLE
Cannot get this working on Pop!_OS 20.10

### ISSUE THREAD

**Issue by eggbean** [Stunkymonkey/nautilus-open-any-terminal#19]
I cannot get this working on Pop!_OS 20.10. I thought it might have to do with this OS having Super+T as the keyboard shortcut to open a terminal.so I tired tried this, but with no success:

     gsettings set com.github.stunkymonkey.nautilus-open-any-terminal keybindings '<Super>t'

Then I tied changing it back to `<Ctrl><Alt>t` again and added <Ctrl><Alt>t to the OS keyboard shortcut settings, but that didn't work either.

How do I get this extension to work on Pop!_OS?

**Comment by eggbean** [comment]
Oh it's okay now. It might have been a reboot that was needed, and simply restarting nautilus wasn't enough. Now I have three entries, due to attempting to set it in multiple ways.

**Comment by Stunkymonkey** [comment]
sorry. i busy at the moment.

Having three entries seems kind of weird. Did you install it three times?

**Comment by eggbean** [comment]
I think it might be due to me installing it for user and as root for all users, while trying to get it to work. 

It's not a problem as I am about to reinstall and apply all my saved settings using ansible.

/home/jason/Pictures/openterm.png

**Comment by Stunkymonkey** [comment]
i understand that you installed it user-wide and system-wide. But that is only two times. I am wondering, where the third comes from.
