### ISSUE TITLE
Hyper does not open on right directory 

### ISSUE THREAD

**Issue by edge7** [Stunkymonkey/nautilus-open-any-terminal#190]
Hi,

Just tried now with hyper and the terminal gets opened but in my home folder.
Do you need more info, logs?

Thanks

**Comment by lvxnull** [comment]
> Hyper does not accept any command line arguments. Please modify the config file instead.

The config file didn't have anything on how to make it inherit CWD from the parent process. Since I don't see any way of making it work, Hyper support will be removed, sorry.
