### ISSUE TITLE
Make file does not work, Pop!_OS jammy 22.04 x86_64

### ISSUE THREAD

**Issue by T-Blitz** [Stunkymonkey/nautilus-open-any-terminal#197]
make -C nautilus_open_any_terminal/locale
make[1]: Entering directory '/home/myname/GitClone/nautilus-open-any-terminal/nautilus_open_any_terminal/locale'
msgfmt -o cs.mo cs.po
make[1]: msgfmt: No such file or directory
make[1]: *** [Makefile:12: cs.mo] Error 127
make[1]: Leaving directory '/home/myname/GitClone/nautilus-open-any-terminal/nautilus_open_any_terminal/locale'
make: *** [Makefile:22: build] Error 2

**Comment by T-Blitz** [comment]
found the "nautilus-extension-any-terminal_0.6.0-1_all.deb" file in  [releases](https://github.com/Stunkymonkey/nautilus-open-any-terminal/releases/tag/0.6.0) now. 
That one works like a charm with no problem.

**Comment by Stunkymonkey** [comment]
so i guess e can close the issue?

**Comment by lvxnull2** [comment]
You got this error because you didn't have `gettext` installed. It should be noted in the README.

**Comment by T-Blitz** [comment]
> You got this error because you didn't have `gettext` installed. It should be noted in the README.

I see, thank you.
Also saw that it was fixed in master already 👍
