### ISSUE TITLE
python-nautilus package not available in POPos

### ISSUE THREAD

**Issue by ankitpal1029** [Stunkymonkey/nautilus-open-any-terminal#20]
Hey i wanted to modify the terminal that opens upon right clicking and selecting open with terminal to alacritty, 
While installing the dependancies i get this message for python-nautilus

![image](https://user-images.githubusercontent.com/49815751/111736492-ef411a00-88a3-11eb-8683-2d7ebfacf2b7.png)

is there some other way i can do what i set out to do?

**Comment by Stunkymonkey** [comment]
is it maybe called `nautilus-python`/`python3-nautilus`?

**Comment by Stunkymonkey** [comment]
i added a note to the README about your problem: fb0d624488b0d9550232eea07d1aff5c9427b03b
