### ISSUE TITLE
Shortcut isn't working

### ISSUE THREAD

**Issue by Laxystem** [Stunkymonkey/nautilus-open-any-terminal#204]
Fedora 41, Wayland, GNOME. Pressing Ctrl Alt T does nothing.

Plus, the shortcut isn't shown in the right click option:
![image](https://github.com/user-attachments/assets/61721d9b-e092-4075-8112-d38c3cd03a7e)

**Comment by Stunkymonkey** [comment]
gnome 43 dropped the keybinding support. So there is nothing I can do. Sorry
