### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by Guray00** [Stunkymonkey/nautilus-open-any-terminal#24]
Is not an issue, but would be nice to have multi language support. I can help with the italian one.

**Comment by lucaslira95** [comment]
I can help with Brazilian Portuguese...

**Comment by Stunkymonkey** [comment]
i have never implemented multi-language with python, but would like to support it.
I could provide the german one.

**Comment by Guray00** [comment]
Maybe this can be a good easy implementation example:
https://github.com/chr314/nautilus-copy-path

**Comment by Stunkymonkey** [comment]
[nautilus-copy-path](https://github.com/chr314/nautilus-copy-path) has a solution for this. But I do not like their solution.

1. what if one language does not have an entry (because in newer version more strings got added)
2. and `nautilus-copy-path` only have fixed strings, and never need to format them.

maybe there are other librarys, that could implement this. not sure how overpowered `gettext` is

**Comment by Stunkymonkey** [comment]
yes we are talking about very few words. but i would like to keep the possibility to introduce bugs to a minimal

**Comment by Stunkymonkey** [comment]
I started working on this today, but I using `gettext` is the best option with the least amount of problems.

And specially it behaves like linux wants it to. And not like the others install files in some non-language-locations.
The translation part is mostly done, but currently all files are coppied by hand. So the Setup is still to be done.

**Comment by Stunkymonkey** [comment]
current progress:
![Screenshot-2022-03-29_161605](https://user-images.githubusercontent.com/1315818/160632147-2eacdfa8-46d6-4b48-bab8-91eebe6af31c.png)
german and swahili is already translated. I have to test it further, but seems good right now

**Comment by Stunkymonkey** [comment]
so the implementation is done. And the next version will include translations.
I am waiting for the next release so you have the chance to add your language as well.

**Comment by Stunkymonkey** [comment]
reminder: I am still waiting for your help in translation. The next release will have support for it.
ping @Guray00 @lucaslira95
