### ISSUE TITLE
Support kermit

### ISSUE THREAD

**Issue by emanuelserpa** [Stunkymonkey/nautilus-open-any-terminal#25]
A simple VTE-based terminal similar to termite.

https://github.com/orhun/kermit

**Comment by Stunkymonkey** [comment]
i would have to use `kermit -e cd /path/to/open/` right?

**Comment by Stunkymonkey** [comment]
please test the latest on `master`

**Comment by emanuelserpa** [comment]
Doesn't work, looks like it's a limitation of kermit. I tried `kermit -c $SHELL cd ` and while it works on the terminal, it doesn't work with the script. I'm suspecting the `cd` does nothing inside open_any_terminal_extension.py.

**Comment by orhun** [comment]
> i would have to use `kermit -e cd /path/to/open/` right?

As far as I understand, you need an argument to launch the terminal in the specified directory. So I added `-w` in the `3.5` release:

```
kermit [-h] [-v] [-d] [-c config] [-t title] [-w workdir] [-e command]

...
[-w workdir] sets the working directory
[-e command] sets the command to execute in terminal
```

e.g.

```
kermit -w /path/to/open/
```
