### ISSUE TITLE
Fully Uninstall

### ISSUE THREAD

**Issue by remlap** [Stunkymonkey/nautilus-open-any-terminal#28]
Hi how do I fully uninstall this, the folder is still showing in dconf-editor and options still showing in nautilus.

**Comment by Stunkymonkey** [comment]
what method did you choose to install the plugin? maybe you are just missing `glib-compile-schemas`?

**Comment by kauanmocelin** [comment]
I ran this command: `pip uninstall nautilus-open-any-terminal` and option on folder nautilus has gone but the entries on dconf-editor persist. How to remove from dconf-editor?

**Comment by Stunkymonkey** [comment]
the entries should remain if they were changed. that is the idea of glib.
Uninstalling for python is not easily possible with `setuptools`. Therefore i created a [script](https://github.com/Stunkymonkey/nautilus-open-any-terminal/blob/master/tools/update-extension-user.sh), which you can run.
