### ISSUE TITLE
The instructions don't explain how to uninstall the app

### ISSUE THREAD

**Issue by Pound-Hash** [Stunkymonkey/nautilus-open-any-terminal#34]
How can we completely uninstall the app?

I tried installing according to the README:

1. `pip install nautilus-open-any-terminal`
2. `nautilus -q`
- Tried `glib-compile-schemas /usr/share/glib-2.0/schemas`, but received an error.
3. So, `glib-compile-schemas ~/.local/share/glib-2.0/schemas/
`
It was working. Then I uninstalled **gnome-terminal** & **nautilus-extension-gnome-terminal** and rebooted. That caused **Nautilus** to no longer show the command in the **context menu**. After that, I had to try `sudo tools/update-extension-user.sh install` & `sudo tools/update-extension-system.sh` install because the original method wasn't working. I got it to work, but then it stopped working again.

I'd like to remove everything.

**Comment by Stunkymonkey** [comment]
`sudo tools/update-extension-system.sh uninstall` is also available. as well as `tools/update-extension-user.sh uninstall`

**Comment by Pound-Hash** [comment]
It worked 😃
