### ISSUE TITLE
Double "open terminalname here"

### ISSUE THREAD

**Issue by theofficialgman** [Stunkymonkey/nautilus-open-any-terminal#41]
both "Open Tilix Here" prompts work, but this is not desired

OS: Ubuntu 22.04 Wayland x86_64
Nautilus 42.0

![Screenshot from 2022-03-30 23-36-57](https://user-images.githubusercontent.com/28281419/160971596-f2cd6249-db97-4c3a-b160-a2303b228829.png)

**Comment by Stunkymonkey** [comment]
i guess you have installed this extension and tilix itself? Everything works as intended. Uninstall this extension and this is fixed.
