### ISSUE TITLE
Uninstalling fails to remove context menu entry

### ISSUE THREAD

**Issue by mj-crabtree** [Stunkymonkey/nautilus-open-any-terminal#49]
Per the title! Not sure if I'm missing something but here's the steps I took when installing & subsequently uninstalling. Hope you can help!

**Steps to reproduce:**
1. `pip install nautilus-open-any-terminal`
2. `nautilus -q`
3. `glib-compile-schemas /usr/share/glib-2.0/schemas`
4. `sudo tools/update-extension-user.sh uninstall`

**Expected behaviour:**
Nautilus' context menu entry for 'Open Gnome-Terminal here' is removed

**Actual Behaviour:**
- Context menu entry persists
- dconf-editor entry persists

Thanks!

**Comment by Stunkymonkey** [comment]
have you tried `glib-compile-schemas ~/.local/share/glib-2.0/schemas/`?

**Comment by Stunkymonkey** [comment]
and are you sure you restarted nautilus with `nautilus -q`?

**Comment by mj-crabtree** [comment]
> have you tried `glib-compile-schemas ~/.local/share/glib-2.0/schemas/`?

affirmative.

`No schema files found: doing nothing`

> and are you sure you restarted nautilus with `nautilus -q`?

affirmative. no joy.

**Comment by Stunkymonkey** [comment]
I see you used the pip install method to install it system-wide. But uninstalled it user-wide:
Please use `sudo tools/update-extension-system.sh uninstall`
then `glib-compile-schemas /usr/share/glib-2.0/schemas`
and at last restart `nautilus -q`

**Comment by mj-crabtree** [comment]
well spotted. went through those steps, no joy.

realised i hadn't attempted to remove the plugin using pip, did that, issue resolved!

![image](https://user-images.githubusercontent.com/66781848/170529203-c38662ee-6bfa-4334-bd73-1480f32b12db.png)

**Comment by Radical4ever** [comment]
hey, im trying to uninstalling it using both ways but it doesnt remove the entry and `glib-compile-schemas /usr/share/glib-2.0/schemas` drops the next thing:`glib-compile-schemas /usr/share/glib-2.0/schemas
Advertencia: el esquema «org.freedesktop.ibus» tiene la ruta «/desktop/ibus/».  Las rutas que empiezan por «/apps/», «/desktop/» o «/system/» están obsoletas.
Advertencia: el esquema «org.freedesktop.ibus.general» tiene la ruta «/desktop/ibus/general/».  Las rutas que empiezan por «/apps/», «/desktop/» o «/system/» están obsoletas.
Advertencia: el esquema «org.freedesktop.ibus.general.hotkey» tiene la ruta «/desktop/ibus/general/hotkey/».  Las rutas que empiezan por «/apps/», «/desktop/» o «/system/» están obsoletas.
Advertencia: el esquema «org.freedesktop.ibus.panel» tiene la ruta «/desktop/ibus/panel/».  Las rutas que empiezan por «/apps/», «/desktop/» o «/system/» están obsoletas.
Advertencia: el esquema «org.freedesktop.ibus.panel.emoji» tiene la ruta «/desktop/ibus/panel/emoji/».  Las rutas que empiezan por «/apps/», «/desktop/» o «/system/» están obsoletas.
Advertencia: el esquema «org.gnome.crypto.cache» tiene la ruta «/desktop/gnome/crypto/cache/».  Las rutas que empiezan por «/apps/», «/desktop/» o «/system/» están obsoletas.
Advertencia: el esquema «org.gnome.crypto.pgp» tiene la ruta «/desktop/gnome/crypto/pgp/».  Las rutas que empiezan por «/apps/», «/desktop/» o «/system/» están obsoletas.
Advertencia: el esquema «org.gnome.system.locale» tiene la ruta «/system/locale/».  Las rutas que empiezan por «/apps/», «/desktop/» o «/system/» están obsoletas.
Advertencia: el esquema «org.gnome.system.proxy» tiene la ruta «/system/proxy/».  Las rutas que empiezan por «/apps/», «/desktop/» o «/system/» están obsoletas.
Advertencia: el esquema «org.gnome.system.proxy.http» tiene la ruta «/system/proxy/http/».  Las rutas que empiezan por «/apps/», «/desktop/» o «/system/» están obsoletas.
Advertencia: el esquema «org.gnome.system.proxy.https» tiene la ruta «/system/proxy/https/».  Las rutas que empiezan por «/apps/», «/desktop/» o «/system/» están obsoletas.
Advertencia: el esquema «org.gnome.system.proxy.ftp» tiene la ruta «/system/proxy/ftp/».  Las rutas que empiezan por «/apps/», «/desktop/» o «/system/» están obsoletas.
Advertencia: el esquema «org.gnome.system.proxy.socks» tiene la ruta «/system/proxy/socks/».  Las rutas que empiezan por «/apps/», «/desktop/» o «/system/» están obsoletas.
No existe la clave «picture-uri-dark» en el esquema «org.gnome.desktop.screensaver» como se especificó en el archivo de sobrescritura «/usr/share/glib-2.0/schemas/10_org.gnome.desktop.screensaver.fedora.gschema.override»; se ignora para esta clave.
`
