### ISSUE TITLE
gnome terminal only opens in a new window

### ISSUE THREAD

**Issue by pietro-coretto** [Stunkymonkey/nautilus-open-any-terminal#56]
I am on Ubuntu 20.04. I installed the software via `pip` and it works except that the gnome-terminal keeps opening in a new window although I did

```
gsettings set com.github.stunkymonkey.nautilus-open-any-terminal new-tab true
```

I also checked on dconf and the setting is correct

![image](https://user-images.githubusercontent.com/71322176/184497552-24bac497-554f-45ba-8305-f52e81f5bbbe.png)

**Comment by Stunkymonkey** [comment]
maybe this is related to the new gnome version. could you please post the parameters, that are available

**Comment by pietro-coretto** [comment]
> maybe this is related to the new gnome version. could you please post the parameters, that are available

it's 

Gnome Tterminal 3.36.2
Using VTE version 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD

**Comment by Stunkymonkey** [comment]
could you please provide `gnome-terminal --help`

**Comment by pietro-coretto** [comment]
this is what I get 

```
Usage:
  gnome-terminal [OPTION…] [-- COMMAND …]

Help Options:
  -h, --help                      Show help options
  --help-all                      Show all help options
  --help-gtk                      Show GTK+ Options
  --help-terminal                 Show terminal options
  --help-window-options           Show per-window options
  --help-terminal-options         Show per-terminal options

Application Options:
  --load-config=FILE              Load a terminal configuration file
  --preferences                   Show preferences window
  -p, --print-environment         Print environment variables to interact with the terminal
  -v, --verbose                   Increase diagnostic verbosity
  -q, --quiet                     Suppress output
  --display=DISPLAY               X display to use
```

**Comment by Stunkymonkey** [comment]
I think there is no option to "open it in a new tab"... Therefore I can not supply it.

**Comment by Stunkymonkey** [comment]
yeah sorry. If you could provide a cli-parameter I would like to implement it. Otherwise it is out of scope for this plugin.
