### ISSUE TITLE
Not compatible with Nautilus 43

### ISSUE THREAD

**Issue by jtojnar** [Stunkymonkey/nautilus-open-any-terminal#57]
The upcoming nautilus-python version is changing/dropping some APIs: https://gnome.pages.gitlab.gnome.org/nautilus-python/nautilus-python-migrating-to-4.html

**Comment by jtojnar** [comment]
@Stunkymonkey  Do you think you could release a new version?

**Comment by Stunkymonkey** [comment]
I am not sure if I should wait for #62 or release it now...

**Comment by jtojnar** [comment]
It’s up to you, we are hopefully merging https://github.com/NixOS/nixpkgs/pull/182618 some time next week so it would be nice to have it before then, otherwise it will be broken.

**Comment by Stunkymonkey** [comment]
@jtojnar please have a look at https://github.com/NixOS/nixpkgs/pull/194097
