### ISSUE TITLE
Entry show twice in context menu

### ISSUE THREAD

**Issue by markfaine** [Stunkymonkey/nautilus-open-any-terminal#66]
As you can see from the attached image.  The context menu entry for opening the terminal appears twice.

![issue](https://user-images.githubusercontent.com/949949/201191780-c7991586-9024-4f59-8d50-6791885eebdd.png)

Ubuntu 22.10

**Comment by Stunkymonkey** [comment]
how did you install it? did one method might be you installed it twice and therefore see it two times.

**Comment by markfaine** [comment]
I used the install script in tools directory.  I don't think that is the problem.  I have even completely removed it multiple times  and also deleted the key from dconf which the uninstall script doesn't seem to do, and then installed it again and every time it shows two times.

**Comment by w4jbm** [comment]
I have the same issue. I did install system-wide and did the setting via the command line. MX Linux 21 using Xfce .

![Screenshot_2022-11-17_10-06-25](https://user-images.githubusercontent.com/26389919/202483125-3c2fb3b8-05bf-473d-8525-f09c2dbdff8a.png)

**Comment by w4jbm** [comment]
Using the info here https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/755 I found that there was both a system and user copy installed even though I only installed the system-wide one. I removed both and then reinstalled only the user copy. That resolved the issue for me.

**Comment by w4jbm** [comment]
I found it in two places:

```
ls /usr/share/nautilus-python/extensions/
ls /home/jbm/.local/share/nautilus-python/extensions/
```

If both have `open_any_terminal_extension.py` in them, it is likely the same issue I had. I haven't had a chance to dig into things around why trying to do the system install also seems to do a user install.

**Comment by lcsjunior** [comment]
@w4jbm 

In the user path temporarily I disabled the extension:

open_any_terminal_extension.py
to
open any terminal extension.py_disabled

After:
nautilus -q

![image](https://user-images.githubusercontent.com/8947621/202951289-6b8aae2e-b692-4071-83fd-a9c9d2ff34f9.png)

**Comment by markfaine** [comment]
> @markfaine please make sure that you do not have the same issue as @w4jbm. This issue has happened to multiple other persons.

I have removed it for now, when I get a chance I will try reinstalling and see if that is the issue.

**Comment by Stunkymonkey** [comment]
if you have it in both locations this means you installed it user wide and system wide. Please stick to one installation.
