### ISSUE TITLE
kitty does not support tabs

### ISSUE THREAD

**Issue by raffaem** [Stunkymonkey/nautilus-open-any-terminal#67]
When I run `nautilus -q`, I get:

> open-any-terminal: terminal is set to "kitty" opening a new window (terminal does not support tabs) 

Yes, it does support tabs!

**Comment by Stunkymonkey** [comment]
I guess this is new. So please tell me the cli-parameters for it and I will implement it.

**Comment by raffaem** [comment]
> I guess this is new. So please tell me the cli-parameters for it and I will implement it.

I uninstalled it because I used GNOME 43. Sorry.

It was a very good project.

Thank you very much.
