### ISSUE TITLE
Keybinding does not work

### ISSUE THREAD

**Issue by raffaem** [Stunkymonkey/nautilus-open-any-terminal#68]
I have run:

```
gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal kitty
gsettings set com.github.stunkymonkey.nautilus-open-any-terminal keybindings '<Ctrl><Alt>t'
gsettings set com.github.stunkymonkey.nautilus-open-any-terminal new-tab true
gsettings set com.github.stunkymonkey.nautilus-open-any-terminal flatpak system
```

and compiled the schemas.

In fact I have the "Open in kitty" context-menu item.

But if I press CTRL+ALT+t, is it supposed to open the terminal?

Because it doesn't work here.

May it be related to the fact I'm on GNOME 43?

**Comment by Stunkymonkey** [comment]
gnome 43 dropped the keybinding support. So there is nothing I can do. Sorry

**Comment by dustdfg** [comment]
> gnome 43 dropped the keybinding support. So there is nothing I can do. Sorry

It looks like in the `dconf-editor` it is possible to show the description field which is empty for now. 
![screen-1707029596](https://github.com/Stunkymonkey/nautilus-open-any-terminal/assets/97330399/980a39cd-a259-4218-a5b8-4650b021fa4c)
I propose to add there description that it doesn't work in gnome 43+
