### ISSUE TITLE
User install instructions shouldn't have "sudo" 

### ISSUE THREAD

**Issue by victante** [Stunkymonkey/nautilus-open-any-terminal#69]
I followed the user-wide install instructions by simply copying the command from the README, with sudo: 

`sudo tools/update-extension-user.sh install`

The `~/` on the script was interpreted as `/root/`, so the files were put there instead of in the user's home folder. I suggest removing the sudo from the README instruction:

`tools/update-extension-user.sh install`

Thanks for the work on this extension!

Edit: I guess the same would apply for the user uninstall instructions.

**Comment by Stunkymonkey** [comment]
you are correct. should be fixed by d4a4a067fc145c154e4671b73f35d2542aabd762
