### ISSUE TITLE
blackbox ignores "new tab" configuration option

### ISSUE THREAD

**Issue by ahvth** [Stunkymonkey/nautilus-open-any-terminal#70]
the title says it all.

reproduction steps:
1. set blackbox as the terminal for the plugin, set open in new tab to on
2. open nautilus
3. open one folder via the plugin, then open another
4. two windows will be opened, ignoring the configuration setting

**Comment by Stunkymonkey** [comment]
the app itself does not support it via command line. If it does please reopen this issue.

**Comment by ahvth** [comment]
opened https://gitlab.gnome.org/raggesilver/blackbox/-/issues/206
