### ISSUE TITLE
Hotkey doesn't work

### ISSUE THREAD

**Issue by tovarish88** [Stunkymonkey/nautilus-open-any-terminal#73]
hello

arch fresh install
nautilus 43.1

every setting by default

thx in advance

**Comment by Stunkymonkey** [comment]
Sadly it is no longer supported: https://gnome.pages.gitlab.gnome.org/nautilus-python/nautilus-python-migrating-to-4.html

> LocationWidgetProvider
The Nautilus.LocationWidgetProvider was removed without replacement. If your script requires it, you can request a new model-based API for your specific use case on the [Nautilus issue tracker](https://gitlab.gnome.org/GNOME/nautilus).

**Comment by tovarish88** [comment]
thx. that's sad
