### ISSUE TITLE
Xterm support

### ISSUE THREAD

**Issue by kaonkaon** [Stunkymonkey/nautilus-open-any-terminal#76]
Im using Xterm and i see that Xterm is not supported.

it'll be so great if you add support to Xterm as well

**Comment by Stunkymonkey** [comment]
could you please tell me the parameters for opening the terminal in a specific folder/working directory

**Comment by kaonkaon** [comment]
idk if this right but this work for me `cd (insert directory) && xterm -hold`

**Comment by Stunkymonkey** [comment]
that is not a good idea with `-hold`. exiting is tricky...
the command should start with `xterm` and not contain any pipeing

**Comment by kaonkaon** [comment]
hmm, i will do more research and then tell you when i find one
