### ISSUE TITLE
Flatpak terminal(Blackbox) not able to open smb mount location

### ISSUE THREAD

**Issue by SoiledBrush** [Stunkymonkey/nautilus-open-any-terminal#77]
Pressing "Open Blackbox Here" in smb mounted folder opens home directory instead. 
This doesn`t happen with kitty, tilix or gnome-terminal installed as system apps.

**Comment by Stunkymonkey** [comment]
could you check if spaces are involved in the folder path?

**Comment by SoiledBrush** [comment]
no, no spaces. The location i'm trying to access is just "/data"

**Comment by Stunkymonkey** [comment]
could you please post the `call` parameters that are used in this function anywhere: https://github.com/Stunkymonkey/nautilus-open-any-terminal/blob/master/nautilus_open_any_terminal/open_any_terminal_extension.py#L172

**Comment by SoiledBrush** [comment]
~/Pictures directory
![image](https://user-images.githubusercontent.com/43366389/215325602-ea8ba09f-d25f-4716-985a-b4e7bd9251ce.png)
/data directory, smd mount. Same behaviour with any subdirectories.
![Screenshot from 2023-01-29 18-18-50](https://user-images.githubusercontent.com/43366389/215325711-2c5aa1db-23ef-4c8e-9bf3-162afe5cd577.png)

**Comment by Stunkymonkey** [comment]
seems to me an upstream issue. please report at: https://gitlab.gnome.org/raggesilver/blackbox

**Comment by SoiledBrush** [comment]
I fixed it by giving blackbox permission to "All system files" via flatseal. 
May be it is how flatpak should behave.
Anyway thanks for your time.
