### ISSUE TITLE
Add wezterm flatpak

### ISSUE THREAD

**Issue by Grafcube** [Stunkymonkey/nautilus-open-any-terminal#81]
I would like to request adding Wezterm's flatpak at `org.wezfurlong.wezterm`.

**Comment by Stunkymonkey** [comment]
could you please tell me the cli parameters for it?

**Comment by Grafcube** [comment]
It should be the same as the native package, Just using `flatpak run org.wezfurlong.wezterm` instead of `wezterm`.

**Comment by Stunkymonkey** [comment]
fixed in: e81f7e3db1646375245cbda9858415f9f0099231
