### ISSUE TITLE
PIP Install depracated in Ubuntu 23.04, package it as a DEB instead.

### ISSUE THREAD

**Issue by yhanruzai** [Stunkymonkey/nautilus-open-any-terminal#86]
Trying to run "pip install nautilus-open-any-terminal"  results in this:

```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
I suppose this is related to Ubuntu, as this doesn't happen on neither Fedora nor Arch. Maybe packaging it as a .DEB would fix it

**Comment by Stunkymonkey** [comment]
packaging could be done by myself, but it does not make much sense, because i am using NixOS. Therefore I will not check if the package is fine.

I am open for a PR. But keep in mind, that I will not test it.

maybe you try: https://github.com/Stunkymonkey/nautilus-open-any-terminal/blob/master/tools/update-extension-system.sh
might fix your problem as well
or run try `pip install nautilus-open-any-terminal --user`

**Comment by lvxnull** [comment]
I made a [MPR package](https://mpr.makedeb.org/packages/nautilus-extension-any-terminal) for this project. You can build it from source already, and later it might be added to the prebuilt MPR repo.

**Comment by Stunkymonkey** [comment]
@lvxnull should we have a CI job for this?

**Comment by lvxnull** [comment]
@Stunkymonkey sure, i wouldn't mind

**Comment by lvxnull** [comment]
The debian package has been included with the release for quite some time now. Closing.
