### ISSUE TITLE
Extra option in the menu

### ISSUE THREAD

**Issue by diego09310** [Stunkymonkey/nautilus-open-any-terminal#87]
I just installed `nautilus-open-any-terminal` using the pip method in Ubuntu 22.04 and I'm seeing this when I right-click on nautilus
![image](https://github.com/Stunkymonkey/nautilus-open-any-terminal/assets/3536529/12221eeb-defd-498f-97e8-711dd4b39877)
Is there any way to remove one of the options? (preferably `Open Wezterm here`) I didn't see it in the dconf-editor options
FYR I have [nautilus-typeahead](https://github.com/lubomir-brindza/nautilus-typeahead) version

**Comment by Stunkymonkey** [comment]
wezterm already shipps the context-menu. simply uninstall this plugin and you are good to go.

**Comment by diego09310** [comment]
Oh, I didn't see it after installing Wezterm, maybe it hadn't loaded.
Thanks!
