### ISSUE TITLE
Extension not having any effect after installation

### ISSUE THREAD

**Issue by Igetin** [Stunkymonkey/nautilus-open-any-terminal#9]
I’ve installed the extension and restarted Nautilus, but the extension seems to not have any effect in the context menu. Here’s my procedure:

```
$ sudo pip3 install nautilus-open-any-terminal
Collecting nautilus-open-any-terminal
  Downloading https://files.pythonhosted.org/packages/72/3d/291b953f12b9f0cacb39290f50885b4fd8a93e47e1655f1df4ea7915361c/nautilus_open_any_terminal-0.2.5.tar.gz
Installing collected packages: nautilus-open-any-terminal
  Running setup.py install for nautilus-open-any-terminal ... done
$ pip3 list | grep nautilus-open-any-terminal
nautilus-open-any-terminal (0.2.5)
$ gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal xfce4-terminal
$ gsettings get com.github.stunkymonkey.nautilus-open-any-terminal terminal
'xfce4-terminal'
$ nautilus -q
$ nautilus
```
When I right click to open the context menu, only the default “Open in Terminal” menu item is shown, which opens GNOME Terminal:

![Nautilus context menu](https://user-images.githubusercontent.com/14016863/79071568-264a9b00-7ce5-11ea-873d-f0d7185f6f04.png)

I then cloned the repository, ran the provided install script and restarted Nautilus again:
```
$ sudo tools/update-extension-system.sh install
'nautilus_open_any_terminal/open_any_terminal_extension.py' -> '/usr/share/nautilus-python/extensions/open_any_terminal_extension.py
$ nautilus -q
$ nautilus
```

Right-clicking still only shows the default “Open in Terminal” menu item. Just in case, I restarted the system, but it didn’t help. Any ideas?

Some details about my system:
```
$ lsb_release -ds
Ubuntu 18.04.4 LTS
$ uname -svrmo
Linux 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 GNU/Linux
$ nautilus --version
GNOME nautilus 3.26.4
```
XFCE version: 4.12

**Comment by Stunkymonkey** [comment]
I will look into it, but it will have to install Ubuntu first. So it will take some time.

**Comment by Stunkymonkey** [comment]
I think this dependency is missing: `sudo apt install python-nautilus`
install this and run the install script again

**Comment by Stunkymonkey** [comment]
there is still another problem with pip and ubuntu

**Comment by Stunkymonkey** [comment]
Thanks for reporting this issue.
Everything is fixed from my side. If the issue persists feel free to reopen
