### ISSUE TITLE
Gets confused with tabs and opened windows when using keybind

### ISSUE THREAD

**Issue by bharathyes** [Stunkymonkey/nautilus-open-any-terminal#90]
Getting odd / partially non-functional behaviour when using the keybind to open in window with multiple tabs or switching to windows with open directory.

With multiple tabs :
The last navigated directory opened in terminal irrespective of from which tab is active when the key is pressed.

With switching windows:
No terminal is opened if,
1. Open a nautilus window 1 and navigate to a directory A
2. Open a nautilus window 2 and navigate to a directory B
3. Switch to window 1. Keypress doesn't open any terminal.
4. If again performing a traversal in window 1, then action opens the proper dir in terminal.

**Comment by Stunkymonkey** [comment]
is there any output if you launch both nautilus windows via terminals?

**Comment by lvxnull** [comment]
I don't think we can fix this one. If anyone has an idea we can always reopen.
