### ISSUE TITLE
extra option in menu (Alacritty)

### ISSUE THREAD

**Issue by UpperAngel** [Stunkymonkey/nautilus-open-any-terminal#96]
installed the extension using pip on Fedora-39
the extension has an extra button

![Screenshot from 2023-11-20 12-18-58](https://github.com/Stunkymonkey/nautilus-open-any-terminal/assets/136232552/b026867e-9d7d-4d95-a3bf-7cf98523dd36)

**Comment by Stunkymonkey** [comment]
how did you install this extension? could be you installed it in multiple ways and therefore see it twice.

**Comment by UpperAngel** [comment]
seems like removing it using pip worked. thanks!
